### ISSUE TITLE
Find, search by role?

### ISSUE THREAD

**Issue by ilp416** [martinrehfeld/role_model#34]
Hi!
Can I find all users with admin role?

**Comment by ilp416** [comment]
Ok. I can.
```
def User.find_by_role role_name
  role = 2**User.valid_roles.index(role_name)
  where "(roles_mask & #{role}) = #{role}"
end
```

**Comment by michaelkirk** [comment]
:+1: for this functionality being included in the core. Would you merge such a PR @martinrehfeld ?

**Comment by martinrehfeld** [comment]
No, I would not. It makes assumptions about the underlying storage/database that I want to keep out of this gem.

**Comment by ilp416** [comment]
Do you mean name of 'roles_mask' field?

**Comment by martinrehfeld** [comment]
Not specifically the field name, this is configurable anyway and the code should pick that up. The assumptions I was referring to are that
a) you assume the data is stored in a SQL database (also one that does support bitwise operations, not sure if this is true for all DBs)
b) on top of that you also assume ActiveRecord by using the `where` method

RoleModel will need to stay agnostic to the underlying storage. One should be able to persist the objects in a NoSQL DB just as well as putting in flat files.
