### ISSUE TITLE
Danger with masking aproach

### ISSUE THREAD

**Issue by ronyvieira** [martinrehfeld/role_model#35]
The mask method uses the index of roles to mask it. If you change a role position in the array or simply add a new role in other position unless last, the given roles will change.

**Comment by martinrehfeld** [comment]
That is correct and the reason why it says `do not change the order if you add more roles later, always append them at the end!` in the README

**Comment by ronyvieira** [comment]
@martinrehfeld  It's not only about changing the order, it's about don't ever change the roles. You are also unable to remove a role... It was just a suggestion to improve the gem because i like the way it handles the roles. Anyway thanks for fast reply :) 
All the best
