### ISSUE TITLE
optional helper methods

### ISSUE THREAD

**Issue by Aryk** [martinrehfeld/role_model#36]
@martinrehfeld would you be open to an option when defining the roles to create a helper function.

So 

```ruby
roles :admin, :manager, :author, helper_methods: true
```

Then:

user.is_admin?
user.is_manager?
user.is_author?

Thoughts?

It would be easier to stub in tests. Also, when passing methods for other gems, they often don't allow for methods with arguments (like if you were to use is?(:admin) ).

**Comment by martinrehfeld** [comment]
Sure. Sounds like a nice feature. How about finding a more descriptive name for the feature set? First attempt: `role_predicates: true`

**Comment by Aryk** [comment]
yeah, role_predicates sounds good. Do you want me to code it and PR?

**Comment by martinrehfeld** [comment]
Your PR is very welcome :-)

**Comment by martinrehfeld** [comment]
It is kinda funny that I already forgot that this functionality is already there :-D I will close this and will work on your PRs independently. I left a lot of comments on them and hope you don't mind. Thanks for taking care!
