### ISSUE TITLE
Assigning roles directly

### ISSUE THREAD

**Issue by Aryk** [martinrehfeld/role_model#39]
Currently to assign roles directly you need to do `user.roles = ['admin']`.

If `dynamic` is not set to false, it will create "is_admin?" and "admin?". 

What about "is_admin = true|false" and "admin = "true|false"

I think if you opt-in for dynamic methods, there should be something to specifically set the roles directly.

Reason this comes up is because right now in order to assign 'admin', we also need to make sure we keep the other roles on the user, so `user.roles = user.roles + ['admin']`

In any case, I envision `user.is_admin = true` would add it in to the other roles only if it doesn't exist, and false would obviously just remove it.

Permission to PR?

**Comment by martinrehfeld** [comment]
So `user.roles = user.roles + ['admin']` not necessary. `user.roles << :admin` will do.

The tradeoff of dynamic setters would be to either further intrude the class' namespace (`#admin=`) or re-use the method names of the predicates (`#is_admin?=`).  Maybe something like `make_admin!` could be ok, but is it really worth it?

**Comment by Aryk** [comment]
@martinrehfeld - well I would argue it's opt-in. If you are creating a user, and can do:

User.create(is_admin: true).is_admin?

I think that makes sense. You are already intruding with is_admin?, may as well round out the methods. Nice thing with is_admin = true, is with that same method you can have is_admin = false,

So you can do `user.update(is_admin: false, banned: true)`, instead of needing to call :<< or :add

If you are still against it, we can close this out, but I like the symmetry of the interface. Again, if you didn't have is_admin? than you shouldn't have is_admin = true|false, but I feel like it's obvious and expected if you already opt-in for the questioner method...

**Comment by martinrehfeld** [comment]
I like the idea of the configurable prefix for the predicates. Defaulting to an empty string would give `admin?` and `admin=` which I personally like way better than `is_admin=` or even `is_admin?=` (yuck). Go ahead! Looking forward to your PR.
