### ISSUE TITLE
Role detection not consistent

### ISSUE THREAD

**Issue by boboroshi** [martinrehfeld/role_model#41]
So I have a model (Lodge) which has admins assigned to it through an editorship table. The super_admin can manage all (cancancan). Users are Devise-based. 

This code renders intermittently:

```
 <% if current_user.roles.include?(:super_admin) %>
        <%= link_to "Permissions",
                    edit_admin_lodge_permissions_path(lodge),
                    class: 'button button-small' %>
 <% end %>
```

So randomly, this button does not show up:
<img width="846" alt="screenshot 2018-04-11 21 22 55" src="https://user-images.githubusercontent.com/2223/38651387-f7909ce4-3dce-11e8-93f7-005e217c40ca.png">

There's nothing different on that particular lodge (or the ones that it affects). Any idea what might be happening? This will also, on different objects and at random, fail for this statement as well:

`<% if can? :manage, lodge %>`

**Comment by martinrehfeld** [comment]
I fail to see from your description and code snippet if and how you are using the `role_model` gem. Do you have that in parallel to what might be an association for the editorship? Have you ruled out that this is in fact a UI problem, e.g. CSS-mishap or view caching related?

Can you please elaborate and show the relevant parts of the `User` model as well as its backing data store schema.

**Comment by boboroshi** [comment]
There's no view caching taking place in this app yet, so I hope that is ruled out. This happens on multiple machines (and is consistent between them at any given time). 

role model (0.8.2) is being used by Canard (https://github.com/james2m/canard/) but perhaps this may be an issue on that gem's implementation. Canard basically takes the abilities files and uses role_model with them. If this is a canard issue, my apologies and I will refile this over there. I felt since it was failing on the role check at random that it would be role_model related.

**Comment by martinrehfeld** [comment]
To be honest, I expect this to be some subtlety in your own code base. Both Canard and RoleModel have been around for a while, so it seems unlikely that a bug right in the core functionality exists. But you never know; feel free to re-open if you find actionable intel.
